### ISSUE TITLE
License fun times (use in browserify)

### ISSUE THREAD

**Issue by goto-bus-stop** [acornjs/acorn-bigint#1]
Now that Node ships with unflagged bigint support, I'd like to add this plugin to [acorn-node](https://github.com/browserify/acorn-node), used by browserify. As I understand the AGPL, simply using it in acorn-node would require acorn-node and browserify to have a compatible license, but they are both MIT. Specifically what I need for acorn-node is to ship a transpiled version of acorn-bigint in-tree, so that it works on all browserify's supported platforms (all the way back to Node 0.8). I saw you relicensed the import-meta plugin under AGPL / Apache, which would seem to allow this use case. Would you be open to doing the same here?

**Comment by adrianheine** [comment]
I changed the license to MIT in 613f74c4b75c8263bba75fb4c469a60add24d300 (released in 0.3.0).
